### PR TITLE
Add support to select all keyboard layouts.

### PR DESCRIPTION
**Pull request by GaiusJocundus**
This will allow all the keyboard layouts supported within vdp-gl to be selected when running mos/vdp.

### CODE REVIEW

**Comment by GaiusJocundus** [comment]
This change is tested and working on Agon Light 2 and Agon Light Origins.

**Comment by lennart-benschop** [comment]
Maybe change the title to mention _keyboard_ layouts explicitly

**Comment by GaiusJocundus** [comment]
> Maybe change the title to mention _keyboard_ layouts explicitly

Thanks, change made.

**Comment by GaiusJocundus** [comment]
Upstream, vdp-gl change that this relies on has been merged: https://github.com/avalonbits/vdp-gl/pull/34

**Comment by stevesims** [comment]
I've added this functionality via #108

**Pull request closed without merging**
